### ISSUE TITLE
Set up GitHub Actions for deploying

### ISSUE THREAD

**Issue by BolasLien** [BolasLien/miniAttic-front-app#30]
To set up GitHub Actions for deploying this Vue.js application to GitHub Pages, follow these steps:

1. Create a directory named `.github/workflows` in your repository.
2. Create a file named `deploy.yml` inside the `.github/workflows` directory.
3. Add the following content to `deploy.yml`:

```yaml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
```

This workflow will automatically build and deploy your Vue.js application to GitHub Pages whenever you push to the `master` branch.
